lib_bot:
    # Publish all joint states -----------------------------------
    joint_state_controller:
        type: joint_state_controller/JointStateController
        publish_rate: 50
        
    height_position_controller:
        type: position_controllers/JointPositionController
        joint: tower_link_elevtor_link_joint
    push_position_controller:
        type: position_controllers/JointPositionController
        joint: elevtor_link_push_link_joint
    jaw_1_position_controller:
        type: position_controllers/JointPositionController
        joint: push_link_jaw_1_joint
    jaw_2_position_controller:
        type: position_controllers/JointPositionController
        joint: push_link_jaw_2_joint

 
